# Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
#remote_theme: open-sdg/open-sdg@2.1.0-dev
remote_theme: brockfanning/open-sdg@chart-tooltip-use-raw

# Replace this title as needed.
title: "Mo's test site"
url: ""
environment: staging

decimal_separator: ','

menu:
  - path: /
    translation_key: 17 goals
  - translation_key: Dropdowns here
    dropdown:
      - path: /https://www.destatis.de/DE/Home/_inhalt.html/
        translation_key: Dropdown field 1
      - path: /https://www.destatis.de/DE/Home/_inhalt.html
        translation_key: Dropdown field 2
        
# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

